# Generated by Django 4.1.2 on 2023-05-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0003_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=50)),
            ],
        ),
    ]
