# Generated by Django 4.1.2 on 2023-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0004_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
