# Generated by Django 4.1.2 on 2023-06-21 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0005_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='moduloApp.sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.CharField(default=4, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero_telefono',
            field=models.IntegerField(),
        ),
    ]
