# Generated by Django 4.1.2 on 2023-06-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0006_alter_producto_options_alter_sucursal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='id_sucursal',
            new_name='nombre',
        ),
    ]
