# Generated by Django 4.1.2 on 2023-06-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0008_alter_devolucion_nombre_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='nombre_sucursal',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_sucursal',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.producto'),
        ),
    ]
