# Generated by Django 4.1.2 on 2023-06-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0010_ingresarsalidaproductos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresarsalidaproductos',
            options={'verbose_name': 'salidaProducto', 'verbose_name_plural': 'salidaProductos'},
        ),
    ]
