# Generated by Django 4.1.2 on 2023-06-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0011_alter_ingresarsalidaproductos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresarsalidaproductos',
            options={'verbose_name': 'salida', 'verbose_name_plural': 'salidas'},
        ),
    ]
