# Generated by Django 4.1.2 on 2023-06-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0012_alter_ingresarsalidaproductos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
