# Generated by Django 4.1.2 on 2023-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0013_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id_producto_stock',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
