# Generated by Django 4.1.2 on 2023-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0014_stock_id_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='nombreProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('id_producto', models.CharField(max_length=100)),
            ],
        ),
    ]
