# Generated by Django 4.1.2 on 2023-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0015_nombreproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombreproducto',
            name='id_producto',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nombreproducto',
            name='nombreProducto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
