# Generated by Django 4.1.2 on 2023-06-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0016_alter_nombreproducto_id_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nombreproducto',
            old_name='nombreProducto',
            new_name='nombre_Producto',
        ),
    ]
