# Generated by Django 4.1.2 on 2023-06-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0017_rename_nombreproducto_nombreproducto_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.nombreproducto'),
        ),
    ]
