# Generated by Django 4.1.2 on 2023-06-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0018_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresarsalidaproductos',
            options={'verbose_name': 'Salida', 'verbose_name_plural': 'Salidas'},
        ),
        migrations.RenameField(
            model_name='nombreproducto',
            old_name='nombre_Producto',
            new_name='nombre_producto',
        ),
    ]
