# Generated by Django 4.1.2 on 2023-06-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0019_alter_ingresarsalidaproductos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
