# Generated by Django 4.1.2 on 2023-06-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0020_alter_devolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
