# Generated by Django 4.1.2 on 2023-06-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0021_alter_devolucion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
    ]
