# Generated by Django 4.1.2 on 2023-06-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0023_usuario_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
