# Generated by Django 4.1.2 on 2023-06-25 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0026_user_producto_fecha_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='hora',
        ),
        migrations.AddField(
            model_name='ingresarsalidaproductos',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
