# Generated by Django 4.1.2 on 2023-06-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0027_remove_devolucion_hora_ingresarsalidaproductos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucion',
            options={'verbose_name': 'Devolucion', 'verbose_name_plural': 'Devoluciones'},
        ),
    ]
