# Generated by Django 4.1.2 on 2023-06-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0028_alter_devolucion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
