# Generated by Django 4.1.2 on 2023-06-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0030_remove_devolucion_hora_alter_devolucion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='motivo',
        ),
    ]
