# Generated by Django 4.1.2 on 2023-06-30 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0033_devolucion_hora_alter_devolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='nombre_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.ingresarsalidaproductos'),
        ),
    ]
