# Generated by Django 4.1.2 on 2023-07-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0037_ingresarentradaproductos'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('id_categoria', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
