# Generated by Django 4.1.2 on 2023-07-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0039_alter_producto_tipo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolucion',
            old_name='nombre_producto',
            new_name='id_venta',
        ),
    ]
