# Generated by Django 4.1.2 on 2023-07-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0041_devolucion_nombre_producto_devolucion_tipo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='tipo_producto',
        ),
    ]
