# Generated by Django 4.1.2 on 2023-07-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0044_remove_devolucion_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloApp.nombreproducto', unique=True),
        ),
    ]
