# Generated by Django 4.1.2 on 2023-07-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0047_usuario_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
