# Generated by Django 4.1.2 on 2023-07-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0048_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='nombre_producto',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
