# Generated by Django 4.1.2 on 2023-07-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0049_devolucion_nombre_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='ingresarsalidaproductos',
            name='id_producto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
