# Generated by Django 4.1.2 on 2023-07-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0051_devolucion_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresarentradaproductos',
            name='id_producto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
