# Generated by Django 4.1.2 on 2023-07-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloApp', '0052_ingresarentradaproductos_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='id_producto',
            field=models.CharField(default='', max_length=50),
        ),
    ]
